### ISSUE TITLE
Telepat couchbase error

### ISSUE THREAD

**Issue by rickyngk** [telepat-io/telepat-docker-compose-files#2]
Hi, not sure if I post in correct repo. I installed Telepat 0.2.2 from docker image. I've got this error sometimes:

    telepatcouchbase_1 | ERROR: unable to init 127.0.0.1 (400) Bad Request
    telepatcouchbase_1 | {u'error': u'Changing data of nodes that are part of provisioned cluster is not supported'}

I try to restart containers but no help.

Please get full log here https://app.box.com/s/u8aqk6c5u3ns0wlnlsa4jxzz7gwfqssb

**Comment by rickyngk** [comment]
I've found on reproduce case:

1. Install fresh share images & telepat from docker
2. Create new admin account using ./telepat.sh
3. Login admin account
4. Create new application
5. Create some new contexts (in my case, I create two new contexts)
6. Delete context one by one. Error occurred after delete last one

Hope that help

**Comment by Mayhem93** [comment]
This is no longer the case as we moved from CB to ElasticSearch. We will get back to CB eventually building the database adapter from scratch.
