### ISSUE TITLE
Issue on AWS ECS: CannotStartContainerError - executable file not found in $PATH

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-docker-compose-files#5]
Hi,

I'm trying to get Telepat running on AWS using Docker Compose with the ECS-CLI tools from Amazon. I have the Shared services running no problem, however when I attempt to install the Telepat API services, I get the following error on every container attempting to run.

````
STOPPED Reason: CannotStartContainerError: API error (500): Cannot start container 54b6caa1f3d8476a7b3538827d4d5017596d696b0877925d1d28a9de735b2433: [8] System error: exec: "node index.js -t sockets_transport -i 0": executable file not found in $PATH
````

Any idea what is happening here? I can't seem to find any useful information on this error. Any help would be greatly appreciated. 

Best,
aaron

**Comment by andreimarinescu** [comment]
Hi Aaron,

Unfortunately we haven't conducted tests on the ECS yet, however the error is related to the fact that the nodeJS executable doesn't seem to be in the path. I'm not sure if the images in ECS are different from the default Docker Registry Hub, my first thought would be to attach to the container and see where the node executable is located at. Then you can change the CMD in the .Dockerfile definition from node to the full path to the nodeJS executable.

**Comment by aaronfranco** [comment]
thanks for the input! I'll look into it.

**Comment by aaronfranco** [comment]
https://github.com/aws/amazon-ecs-cli/issues/78
